name: dependabot-auto-merge

on:
  pull_request_target:

permissions: write-all

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v4

      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/dependabot-auto-merge.yml

