name: Build and Test
 
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  workflow_dispatch:

permissions: write-all

jobs:
  test:
    strategy:
      matrix:
        node-version: [22.x]

    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v5

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: |
          - recursive: true
            args: [--no-frozen-lockfile]

    - uses: oven-sh/setup-bun@v2

    - name: Build and Unittest
      run: bun run --bun all
